# Generated by Django 3.2.2 on 2021-05-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calladvisor', '0002_auto_20210513_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='img_field',
        ),
    ]
